### ISSUE TITLE
Is skip_precompile the clearest name?

### ISSUE THREAD

**Issue by oxinabox** [JuliaLang/PrecompileTools.jl#2]
Per the docs if the `skip_precompile` preference is set, the code in `Precompiler.@setup` and `Precompiler.@cache` will be skipped.

However, this is not all the work that julia does during precompilation.
e.g. it will still run any global statements outside these blocks and cache those.
As such, when you do something that triggered precompilation, e.g. changing the package `Foo` then running `using Foo`,
precompilation will run, and thus the message `Precompiling Foo` will be displayed.

This is likely to confuse people who don't understand that multiple different things are included under the precompilation step.
And will make people think that their setting didn't work.

As such I think we should consider a different preference name.

**Comment by timholy** [comment]
Sounds good to me. What do you suggest?

**Comment by timholy** [comment]
Maybe a couple of options:
- `skip_precompiler`
- `minimal_precompile`
- `precompile_min`
- `skip_precompile_workload`

Other ideas are welcome.

**Comment by timholy** [comment]
I lost 15 minutes during development of Precompiler to being inconsistent about whether I used `skip_precompile` or `skip_precompiler`. So your worry is well-founded.

**Comment by IanButterworth** [comment]
Oh right, because preferences aren't checked for name correctness against supported options?

**Comment by KristofferC** [comment]
One drawback with calling this package "Precompiler" is indeed that it is just hard to separate the act of normal package precompilation and that of a running a special work load. Maybe there should be some kind of prefix to it (Snoop? :D :D) to make it stand out. "DeepPrecompile" or something...

**Comment by DilumAluthge** [comment]
PrecompiledWorkloads.jl? And then the preference would be `skip_precompiled_workloads`?

**Comment by timholy** [comment]
Some options:
- PrecompiledWorkloads (with `skip_precompiled_workloads`):
  + pro: an accurate statement of "how it's used"
  + potential con: tied to the "run a workload" mechanism. If we later add additional mechanisms for easy precompilation (ones that don't require actually running the workload), can those go in this package or do we need a new package?
- CacheSpecializations (with `skip_specializations`):
  + pro: an accurate statement of "what it's doing"
  + con: more technical, likely not as easily searchable for most users
- CompileHelper (with `skip_compilehelper`):
  + pro: an accurate statement of "how it's used"
  + con: maybe slightly less searchable without the "pre", but partially offset by the reduced confusion about why things are still precompiling even when disabled

I welcome more ideas.

**Comment by KristofferC** [comment]
Maybe the package name and the preference name does not have to exactly follow eachother? So the package could be something like "PrecompileTools` while the option is still `skip_extra_precompile` or `skip_precompile_workload` or something. When there is some new mechanism it can just have another preference name, but the package name is still general enough to encompass it?

**Comment by mbauman** [comment]
There really are just four names in this package, currently: `Precompiler`, `@setup`, `@cache` and `skip_precompile`.

We also have [`Base.compilecache`](https://docs.julialang.org/en/v1/base/base/#Base.compilecache), [`Base.__precompile__`](https://docs.julialang.org/en/v1/base/base/#Base.__precompile__), [`Pkg.precompile`](https://pkgdocs.julialang.org/v1/api/#Pkg.precompile), and [`ENV["JULIA_PKG_PRECOMPILE_AUTO"]`](https://docs.julialang.org/en/v1/manual/environment-variables/#JULIA_PKG_PRECOMPILE_AUTO).

I think I like PrecompileTools the best, too.  Maybe rename `@cache` to `@workload`.  And then I'd advocate for inverting the pref name to not be negative — something like setting `precompile_workload` => `false` (defaulting to true).

**Comment by timholy** [comment]
I like those suggestions, with one exception: I'd prefer a verb (like `@cache`) to a noun (like `@workload`). But `@cache` is a bit technical, so it's far from ideal.

**Comment by IanButterworth** [comment]
Maybe a simple `PrecompileTools.@compile`?

**Comment by KristofferC** [comment]
Something with "deep" maybe? Or "trace"? `PrecompileTools.@compile_trace_deep`. `PrecompileTools.@tracecompile`. etc?

**Comment by KristofferC** [comment]
`PrecompileTools.@setup` -> `PrecompileTools.@setup_workload` maybe, to have it symmetric?

**Comment by timholy** [comment]
Then I think we can also export both names.

**Comment by timholy** [comment]
Registration is underway: https://github.com/JuliaRegistries/General/pull/82046
