### ISSUE TITLE
Understanding Preference Settings

### ISSUE THREAD

**Issue by bradcarman** [JuliaLang/PrecompileTools.jl#25]
The documentation about reducing the cost of precompilation states "You can also specify additional packages (e.g., dependencies of MyPackage) if you're co-developing a suite of packages.".  How is this done?  It's not clear how I list those packages.

Additional question: is it possible to turn off precompilation workloads all together for my development environment for all packages/dependencies?  The reason why I want this is because I'm creating a system image that I would like to keep as small as possible, therefore I only want to include compilation for my specific code.  Is this possible?

**Comment by timholy** [comment]
It's exactly the same: just set `"precompile_workload" => false` on each such package. `?set_preferences!` will show you various options: you can pass a module or a UUID.

Alternatively, you could turn it off for one or two and then make the (fairly obvious) edits to `LocalPreferences.toml` manually.

I'd be most appreciative if you submitted a pull request (https://github.com/JuliaLang/PrecompileTools.jl/blob/main/docs/src/index.md and click the pencil icon) to make this clearer to other readers! It's often hard for those who wrote the code to understand what about the documentation is unclear (we know too much about the internals to approach the documentation with the same mindset).

**Comment by timholy** [comment]
I'd be supportive of an option to disable it altogether.
